### ISSUE TITLE
Add publication list from bib file

### ISSUE THREAD

**Issue by jefferis** [natverse/natverse_hugo#24]
I don't think there's any automated way to collect publications. Anything that cites Manton et al is a good candidate, but there are plenty of others. So I think the best way is to collect a `.bib` file and use it like this:

https://github.com/rbind/blogdown-demo/blob/master/content/post/2017-08-28-adding-citations-to-posts.Rmd

**Comment by jefferis** [comment]
@jdmanton maybe you could look at this one. The bib file is in the google drive folder 
`2019nat/natverse-papers.bib`

**Comment by jdmanton** [comment]
I failed at diagnosing why, but the instructions at [https://github.com/rbind/blogdown-demo/blob/master/content/post/2017-08-28-adding-citations-to-posts.Rmd] did nothing, just leaving the raw tags in the final page. I also tried writing a custom YAML processor, based on converting the `.bib` file using `pandoc-citeproc` but that ended up looking like a lot of work, so I resorted to a hand-curated approach with LaTeX -> Word -> RegEx, added in 3e4451e.

**Comment by jefferis** [comment]
OK. Thanks. Just checking, but does it matter if the file is an `.Rmd` vs `.md`?

**Comment by jdmanton** [comment]
> OK. Thanks. Just checking, but does it matter if the file is an .Rmd vs .md?

I'm an idiot. I'll push shortly...

**Comment by jdmanton** [comment]
Autogenerated publication list added in 7634e2a (albeit one ordered by surname of first author, not year).

**Comment by jefferis** [comment]
Super. That's great! We can look into the ordering at some point, but this great.
