### ISSUE TITLE
Link broken for natverse package nat.flybrains

### ISSUE THREAD

**Issue by mmc46** [natverse/natverse_hugo#31]
In http://natverse.org/packages/, package `nat.flybrains`

links to https://jefferislab.github.io/nat.flybrains/ which gives a 404 error.

**Comment by jefferis** [comment]
Thanks @SridharJagannathan. Those two additional repos are now moved.

**Comment by SridharJagannathan** [comment]
@jefferis thanks for this, everything seems working except for the `neuromorphr` package the page https://natverse.github.io/neuromorphr is suffering from too many redirects.

**Comment by jefferis** [comment]
Thanks! Do you have any idea why that page is behaving differently? I don’t see evidence of a special config for that page.

**Comment by SridharJagannathan** [comment]
Fixed it now, but I think the `neuromorphr` pkg would be good to adapt `_pkgdown.yml` settings like other projects. Also there are many places where jefferislab is still mentioned in that package, so would be good for the author to do a full check.

**Comment by SridharJagannathan** [comment]
Also the main reason why it was failing (`neuromorphr`) before was that the file `docs/index.html` was using the URL being present in the `DESCRIPTION`. But as I said before would be good to have some settings put in `_pkgdown.yml`
