### ISSUE TITLE
Figure out a strategy to autogenerate GitHub Pages site

### ISSUE THREAD

**Issue by jefferis** [natverse/natverse_hugo#4]
See https://gohugo.io/hosting-and-deployment/hosting-on-github/ which basically advises two separate repositories (with the `orgname.github.io` repo as a git submodule in the location of the `public` folder).

**Comment by SridharJagannathan** [comment]
Closed via #10, I used the `travis` strategy from https://www.freecodecamp.org/news/two-ways-to-deploy-a-public-github-pages-site-from-a-private-hugo-repository-627312ec63b9/
