### ISSUE TITLE
Complete packages page

### ISSUE THREAD

**Issue by jefferis** [natverse/natverse_hugo#5]
* Consider scraping package descriptions from R `DESCRIPTION` files.
* Add a section for external packages
* think about how to group logically related packages
* @SridharJagannathan could add the list of packages that we noted in his checkout

**Comment by SridharJagannathan** [comment]
List of packages per discussion:
```
packages
└───Set#1
   │   nat
   │   nat.templatebrains
   │   nat.nblast
└───Set#2
   │   catmaid
   │   neuprintr
   │   drvid
   │   neuromorphr
└───Set#3
   │   elmr
   │   nat.flybrains
   │   flycircuit
└───Set#4 
   │   nabor
└───Set#5 (external packages)
   │   rgl
   │   igraph
   │   alphashape3d
   │   Rvcg
   │   Morpho

```

**Comment by SridharJagannathan** [comment]
@jefferis : Can you please check the latest (https://natverse.github.io/packages/) and give feedback.

**Comment by jefferis** [comment]
Hi @SridharJagannathan, thanks, this looks very good! I A few things I spotted

* could the hex logos hyperlink to the packages?
* neurprintr -> neuprintr (typo)
* neuromorphr
* nabor description finishes at the period following the e of e.g. (probably nor intended)
* I would link all of the external packages to their CRAN page unless they have a pkgdown doc site (I don't think they do)

@alexanderbates any comments?

**Comment by SridharJagannathan** [comment]
@jefferis I have fixed all the comments except neuromorphr, what do you mean here?

**Comment by alexanderbates** [comment]
Just that the description is a bit lacking

**Comment by SridharJagannathan** [comment]
> Just that the description is a bit lacking

They are automatically scraped from the description in the `r` package and I use only the first line (otherwise it becomes a bit crowded). Maybe then we need to change the actual description in the `r` package.

**Comment by alexanderbates** [comment]
So the '.' there is for NeuroMorpho.org, the full description is:

> Access to the NeuroMorpho.org repository (version 7.7 ) and several other single-cell neuron databases, enabling users to easily find and use neurons in this repository with nat family packages.

Maybe the full descriptions are better? And if some are too long, we should seek to change them in the package?

For now, I can remove .org

**Comment by SridharJagannathan** [comment]
Closing this now, as all issues seem to be updated.
