### ISSUE TITLE
Setup the menu headers for the site

### ISSUE THREAD

**Issue by jefferis** [natverse/natverse_hugo#6]
* Again @SridharJagannathan has the list we agreed

**Comment by jefferis** [comment]
@SridharJagannathan could you post that list here when you have a moment?

**Comment by SridharJagannathan** [comment]
```
│
└───Install
└───Packages
└───Gallery
└───Learn
└───Articles
└───Publications
└───Help
└───About (us) Team?
 ```

**Comment by jefferis** [comment]
So we should leave the Contribute header as well then (but I need to edit it!)

**Comment by jefferis** [comment]
Another Idea instead of Gallery is Showcase (see https://www.htmlwidgets.org/index.html)

**Comment by SridharJagannathan** [comment]
@jefferis : Can you please check the latest (https://natverse.github.io/) and give feedback.

**Comment by jefferis** [comment]
I think we can consider this one done for now although some sections still need work.

**Comment by jefferis** [comment]
Thanks @SridharJagannathan!
